spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus_ecommerce?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hhplus
    password: hhplus
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN